### ISSUE TITLE
Use useContext in Class

### ISSUE THREAD

**Issue by sw-tt-jethanandnandpal** [milansusnjar/blogL10n#2]
Hi @milansusnjar,

Thanks for the nice tutorial. I have an one query, how to use useContext in class. I have tried but it gives me hooks error. 

Can you please let us know the resolutions to resolved it.

Thanks in advance...!!!

**Comment by Yozine** [comment]
I ran into the same issue and fixed it by ' consuming the provider '. 

It would look something like:
`<LocalizationContext.Consumer>
            {context => (
              <TextInput
                style={styles.input}
                placeholder={context.translations.search_placeholder}
                selectionColor={Colors.regularGrey}
                placeholderTextColor={Colors.lightGrey}
                onChangeText={query => this.setState({query})}
                value={this.state.query}
                onSubmitEditing={() => this.open(this.state.query)}
              />
            )}
          </LocalizationContext.Consumer>`

**Comment by sw-tt-jethanandnandpal** [comment]
@milansusnjar,  actually I am new to react and try to resolve to use the 'useContext' in class component but didn't get success. If you don't mine then can you please share the demo in which you fixed the useContext issue and use the 'useContext' in class component. It will really help me because I am stuck from last few days.

Thanks in advance...!!!

**Comment by sw-tt-jethanandnandpal** [comment]
@milansusnjar, we have also tried with the **'I18n'** but in this drawers and navigation labels not changed.

**Comment by milansusnjar** [comment]
You can't use hooks in Class components.
We have used Higher Order Components for localization with Classes before.
